from django.urls import path     
from . import views

urlpatterns = [
    path('', views.register),
    path('login/', views.login),
    path('login_user',views.login_user),
    path('register/', views.register),
    path('dashboard/', views.dashboard),
    path('forgot_password/', views.forgot_password),
    path('create_user', views.create_user),
    path('find_email', views.find_email),
    path('secret_q/<int:id>', views.secret_q),
    path('answer_secret_q', views.answer_secret_q),
    path('reset_password/<int:id>', views.reset_password),
    path('resetting_forgotten_password', views.resetting_forgotten_password),
    path('logout', views.logout),   
    path('create/event', views.create_event_page),
    path('create_event', views.create_event),
    path('cancel_event/<int:id>',views.cancel_event),
    path('search', views.search),
    path('view_event/<int:id>', views.view_event),
    path('unjoin/<int:id>',views.unjoin_event),
    path('join/<int:id>',views.join_event),
    path('account/<int:id>', views.view_account),
    path('update_user/<int:id>', views.update_user),
    path('create_message/<int:id>',views.create_message),
    path('delete_message/<int:id>/<int:ide>',views.delete_message),
    path('edit_message/<int:id>/<int:ide>',views.edit_message),
    path('message_edited/<int:id>/<int:ide>',views.message_edited),
]
