# Generated by Django 2.2.4 on 2023-02-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_events_app', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_creator',
            new_name='user',
        ),
    ]
