# Generated by Django 2.2.4 on 2023-02-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_events_app', '0007_attending_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attendees', to='neighborhood_events_app.User'),
        ),
        migrations.DeleteModel(
            name='Attending_event',
        ),
    ]
