# Generated by Django 2.2.4 on 2023-03-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_events_app', '0009_auto_20230228_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_answer',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='secret_question',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
